In [1]:
import cv2
import numpy as np

img = cv2.imread("people.jpg")
print(img)
print("hsjıjdsfkdfpgş")

[[[120 116  98]
  [115 110  95]
  [118 112 101]
  ...
  [215 213 212]
  [215 213 212]
  [215 213 212]]

 [[119 115  97]
  [114 109  94]
  [118 112 101]
  ...
  [215 213 212]
  [215 213 212]
  [215 213 212]]

 [[116 112  94]
  [112 107  92]
  [116 110  99]
  ...
  [215 213 212]
  [215 213 212]
  [215 213 212]]

 ...

 [[ 30  29  33]
  [ 30  29  33]
  [ 30  29  33]
  ...
  [150 149 151]
  [150 149 151]
  [150 149 151]]

 [[ 31  30  34]
  [ 31  30  34]
  [ 32  31  35]
  ...
  [150 149 151]
  [150 149 151]
  [150 149 151]]

 [[ 32  31  35]
  [ 32  31  35]
  [ 33  32  36]
  ...
  [148 150 151]
  [148 150 151]
  [148 150 151]]]
hsjıjdsfkdfpgş


In [2]:
img.shape

(427, 640, 3)

In [3]:
img_width = img.shape[1]
img_height = img.shape[0]

In [4]:
img_width

640

In [5]:
img_blob = cv2.dnn.blobFromImage(img, 1/255, (416,416), swapRB = True, crop = False )  #görüntüyü 4boyutlu tensöre çevirdik, modelimiz 416 ololanı indirdik
#crop false çünkü resmi kırpmasını istemiyoruz

In [6]:
img_blob

array([[[[0.3803922 , 0.3921569 , 0.40784317, ..., 0.82745105,
          0.8313726 , 0.8313726 ],
         [0.37647063, 0.38823533, 0.4039216 , ..., 0.82745105,
          0.8313726 , 0.8313726 ],
         [0.3647059 , 0.3803922 , 0.40000004, ..., 0.82745105,
          0.8313726 , 0.8313726 ],
         ...,
         [0.12941177, 0.12941177, 0.13333334, ..., 0.5921569 ,
          0.5921569 , 0.5921569 ],
         [0.13333334, 0.13725491, 0.14117648, ..., 0.5921569 ,
          0.5921569 , 0.5921569 ],
         [0.13725491, 0.14117648, 0.14117648, ..., 0.5921569 ,
          0.5921569 , 0.5921569 ]],

        [[0.44705886, 0.43529415, 0.45098042, ..., 0.8313726 ,
          0.8352942 , 0.8352942 ],
         [0.4431373 , 0.43529415, 0.45098042, ..., 0.8313726 ,
          0.8352942 , 0.8352942 ],
         [0.43137258, 0.427451  , 0.44705886, ..., 0.8352942 ,
          0.8352942 , 0.8352942 ],
         ...,
         [0.1137255 , 0.1137255 , 0.11764707, ..., 0.58431375,
          0.58431375, 0.5

In [7]:
labels = ["person", "train", "laptop", "bicycle", "motorcycle", "airplane", "bus", "trafficlight", 
         "firehydrant", "stopsign", "dog", "horse", "sheep", "cow", "elephant", "bear", "umbrella", 
          "handbag", "bottle", "keyboard", "book", "clock", "vase", "book", "apple", "banana", "mouse",
          "train", "truck", "boat", "parkingmeter", "bench", "bird", "cat", "zebra", "giraffe", "backpack",
          "tie", "suitcase", "frisbee", "skis", "snowboard", "sportsball", "kite", "baseballbat", "basebaliglove",
          "skateboard", "surfboard", "tennisracket", "wineglass", "cup", "fork", "knife", "spoon", "bowl",
          "sandwich", "orange", "broccoli", "carrot", "hotdog", "pizza","donut","cake", "chair", "sofa",
          "pattedplant","bed", "diningtable", "toilet", "tvmonitor", "remote","cellphone", "mocrowave", "oven",
          "toaster", "sink", "refrigerator", "scissors", "teddybear", "hairdrier", "toothbrush"]

In [8]:
colors = ["0,255,255", "0,0,255", "255,255,0", "0,255,0"]
colors = [np.array(color.split(",")).astype("int") for color in colors]
colors = np.array(colors)
colors = np.tile(colors,(18,1))  
#tile fonksiyonu colors matrisini aşağıya doğru 18 kere çoğğalttı yana doğru 1 yerine 2 olsaydı 2 kere çoğaltırdı


In [9]:
colors

array([[  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0, 255],
       [255, 255,   0],
       [  0, 255,   0],
       [  0, 255, 255],
       [  0,   0

In [10]:
model = cv2.dnn.readNetFromDarknet("model/yolov3.cfg", "model/yolov3.weights")

In [11]:
layers = model.getLayerNames()
layers

['conv_0',
 'bn_0',
 'relu_0',
 'conv_1',
 'bn_1',
 'relu_1',
 'conv_2',
 'bn_2',
 'relu_2',
 'conv_3',
 'bn_3',
 'relu_3',
 'shortcut_4',
 'conv_5',
 'bn_5',
 'relu_5',
 'conv_6',
 'bn_6',
 'relu_6',
 'conv_7',
 'bn_7',
 'relu_7',
 'shortcut_8',
 'conv_9',
 'bn_9',
 'relu_9',
 'conv_10',
 'bn_10',
 'relu_10',
 'shortcut_11',
 'conv_12',
 'bn_12',
 'relu_12',
 'conv_13',
 'bn_13',
 'relu_13',
 'conv_14',
 'bn_14',
 'relu_14',
 'shortcut_15',
 'conv_16',
 'bn_16',
 'relu_16',
 'conv_17',
 'bn_17',
 'relu_17',
 'shortcut_18',
 'conv_19',
 'bn_19',
 'relu_19',
 'conv_20',
 'bn_20',
 'relu_20',
 'shortcut_21',
 'conv_22',
 'bn_22',
 'relu_22',
 'conv_23',
 'bn_23',
 'relu_23',
 'shortcut_24',
 'conv_25',
 'bn_25',
 'relu_25',
 'conv_26',
 'bn_26',
 'relu_26',
 'shortcut_27',
 'conv_28',
 'bn_28',
 'relu_28',
 'conv_29',
 'bn_29',
 'relu_29',
 'shortcut_30',
 'conv_31',
 'bn_31',
 'relu_31',
 'conv_32',
 'bn_32',
 'relu_32',
 'shortcut_33',
 'conv_34',
 'bn_34',
 'relu_34',
 'conv_35',
 'bn

In [12]:
output_layers = [layers[layer[0]-1] for layer in model.getUnconnectedOutLayers()]
output_layers

['yolo_82', 'yolo_94', 'yolo_106']

In [13]:
model.setInput(img_blob)

In [14]:
detection_layers = model.forward(output_layers)
detection_layers

[array([[0.03974058, 0.05042557, 0.48130545, ..., 0.        , 0.        ,
         0.        ],
        [0.04463822, 0.03315829, 0.30353582, ..., 0.        , 0.        ,
         0.        ],
        [0.04665059, 0.03384104, 0.81447816, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.96136063, 0.9509623 , 0.45055807, ..., 0.        , 0.        ,
         0.        ],
        [0.96341693, 0.9642481 , 0.29853463, ..., 0.        , 0.        ,
         0.        ],
        [0.9674819 , 0.95940435, 0.8049359 , ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 array([[0.01554258, 0.02663833, 0.0451524 , ..., 0.        , 0.        ,
         0.        ],
        [0.01827556, 0.02224421, 0.40346014, ..., 0.        , 0.        ,
         0.        ],
        [0.02250212, 0.01666359, 0.0769702 , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.97813797, 0.97711813, 0.03838282, ..., 0.        , 0.        ,
         0.        

In [15]:
for detection_layer in detection_layers:
    for object_detection in detection_layer:
        scores = object_detection[5:]
        predicted_id = np.argmax(scores)
        confidence = scores[predicted_id]
        
        if confidence > 0.40:
            label = labels[predicted_id]
            bounding_box = object_detection[0:4] * np.array([img_width, img_height, img_width, img_height ])
            (box_center_x, box_center_y, box_width, box_height) = bounding_box.astype("int")
            
            start_x = int(box_center_x - (box_width/2))
            start_y = int(box_center_y - (box_height/2))
            
            end_x = start_x + box_width
            end_y = start_y + box_height
            
            box_color = colors[predicted_id]
            box_color = [int(each) for each in box_color]
            
            label = "{}: {:.2f}%".format(label, confidence*100)
            print("predicted object {}".format(label)) #güven skorunu ekrana yazdırmak için
            
            cv2.rectangle(img, (start_x, start_y), (end_x, end_y), box_color, 1)
            cv2.putText(img, label, (start_x, start_y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, box_color, 1)
            
            
            
        

predicted object cake: 99.40%
predicted object person: 99.92%
predicted object person: 99.86%
predicted object train: 74.45%
predicted object carrot: 46.50%
predicted object snowboard: 78.01%
predicted object snowboard: 76.62%


In [16]:
cv2.imshow("Detection Window" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()